[tool]
id = "openapi"

[[dependency]]
path = "../openapi-cli/build/libs/openapi-cli-2.4.0-SNAPSHOT.jar"

[[dependency]]
path = "../openapi-core/build/libs/openapi-core-2.4.0-SNAPSHOT.jar"

[[dependency]]
path = "../ballerina-to-openapi/build/libs/ballerina-to-openapi-2.4.0-SNAPSHOT.jar"

[[dependency]]
path = "../openapi-bal-task-plugin/build/libs/openapi-bal-task-plugin-2.4.0-SNAPSHOT.jar"
