[package]
org= "ballerina"
name= "openapi"
version= "1.7.0"

[[platform.java17.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-1.7.0-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "1.7.0-SNAPSHOT"
