[plugin]
id = "openapi-tools"
class = "io.ballerina.openapi.validator.OpenAPIValidatorPlugin"

[[dependency]]
path = "../openapi-validator/build/libs/openapi-validator-1.7.0-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "1.7.0-SNAPSHOT"
