[plugin]
id = "openapi-tools"
class = "io.ballerina.openapi.validator.OpenAPIValidatorPlugin"

[[dependency]]
path = "../openapi-validator/build/libs/openapi-validator-2.3.2-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "2.3.2-SNAPSHOT"
