[package]
org = "ballerina"
name = "tool.openapi"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["openapi", "openapi tool", "swagger", "oas", "openapi generator"]
license = ["Apache-2.0"]
